#!/usr/bin/env python3
"""Generate build-time photo dimensions for the photo guide mosaic.

The browser needs each photograph's aspect ratio before its thumbnail has
downloaded, otherwise the guide cannot reserve a stable rectangular layout.
This script combines the remote URLs used by Hugo markdown with the local
manifest produced while preparing thumbnails.

Usage:
  ./scripts/generate-photo-metrics.py
  ./scripts/generate-photo-metrics.py --manifest /path/to/photo-manifest.tsv
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path


IMAGE_RE = re.compile(
    r"!\[[^\]]*\]\((https://assets\.wujipeng\.com/[^)\s]+)\)",
    re.IGNORECASE,
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path.home() / "Pictures" / "photo-manifest.tsv",
        help="TSV manifest written by the local thumbnail workflow",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "data" / "photo_metrics.toml",
        help="Hugo data file to write",
    )
    args = parser.parse_args()

    with args.manifest.open(encoding="utf-8", newline="") as stream:
        metrics = {
            Path(row["original"]).stem: (int(row["orig_width"]), int(row["orig_height"]))
            for row in csv.DictReader(stream, delimiter="\t")
            if row.get("original")
        }

    project_root = Path(__file__).resolve().parents[1]
    roots = [project_root / "content" / "photos"]
    used: set[str] = set()
    for root in roots:
        for source in sorted((*root.glob("*.md"), *root.glob("*.html"))):
            for match in IMAGE_RE.finditer(source.read_text(encoding="utf-8")):
                stem = Path(match.group(1)).stem
                if stem not in metrics:
                    raise SystemExit(f"No manifest dimensions for {match.group(1)}")
                used.add(stem)

    lines = [
        "# Generated by scripts/generate-photo-metrics.py; do not edit by hand.",
        "",
    ]
    for stem in sorted(used):
        width, height = metrics[stem]
        lines += [
            "[[images]]",
            f'stem = "{stem}"',
            f"width = {width}",
            f"height = {height}",
            "",
        ]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(used)} photo metrics to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
